title: "Zizheng (Barry) Zhao"
description: "PhD Candidate in Finance, University of Connecticut"
url: "https://B-zhao126.github.io"   # 等 barryzhao.com 生效后再改
baseurl: ""
repository: "B-zhao126/B-zhao126.github.io"

author:
  avatar: "profile.jpg"  
  name: "Zizheng (Barry) Zhao"
  location: "Storrs, CT"
  employer: "University of Connecticut"
  email: "zizheng.zhao@uconn.edu"
